# Generated by Django 2.2.7 on 2019-12-02 15:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaceReview',
            new_name='TourReview',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place',
            new_name='tour',
        ),
    ]
