# Generated by Django 2.2.7 on 2019-12-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191202_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='food',
        ),
        migrations.AlterField(
            model_name='place',
            name='stay',
            field=models.ManyToManyField(blank=True, to='core.StayReview'),
        ),
        migrations.AlterField(
            model_name='place',
            name='tour',
            field=models.ManyToManyField(blank=True, to='core.TourReview'),
        ),
    ]
