# Generated by Django 2.2.7 on 2019-12-10 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_foodreview_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='stay',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tour',
        ),
        migrations.AddField(
            model_name='stayreview',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Place'),
        ),
        migrations.AddField(
            model_name='tourreview',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Place'),
        ),
    ]
